# Generated by Django 3.2.5 on 2021-07-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_app', '0003_auto_20210722_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
