# Generated by Django 3.2.5 on 2021-07-21 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processing_app', '0004_auto_20210722_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='statuses',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='processing_app.statusapplication'),
            preserve_default=False,
        ),
    ]
